#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  prefix: home
  resource: routes/main/home/index.yaml

restaurant:
  prefix: restaurant
  resource: routes/main/cuisine/restaurant.yaml